const $=s=>document.querySelector(s), API='/paleru-social';
const words={en:{title:'Paleru Congress',subtitle:'Together for development',install:'Install',internal:"MEMBERS' NETWORK",welcome:'Service. Progress. Unity.',intro:'Share development work and strengthen coordination across Paleru.',live:'Live activity feed',maps:'Places on Maps',shareUpdate:'Share an update',inspire:'Let good work inspire every mandal',name:'Your name',activity:'Development or party activity',place:'Place / village',photo:'Photo',publish:'Publish update',community:'COMMUNITY',latest:'Latest activities',more:'Load more',home:'Home',post:'Post',help:'Install',comments:'Comments',send:'Send',installTitle:'Install this app',iosGuide:'On iPhone: open in Safari, tap Share, then “Add to Home Screen”.',androidGuide:'On Android: open the browser menu and tap “Install app”.',noPosts:'The story begins here',firstPost:'Share the first activity from your village.'},te:{title:'పాలేరు కాంగ్రెస్',subtitle:'అభివృద్ధి కోసం కలిసి',install:'ఇన్‌స్టాల్',internal:'సభ్యుల వేదిక',welcome:'సేవ. ప్రగతి. ఐక్యత.',intro:'అభివృద్ధి పనులను పంచుకొని పాలేరు అంతటా సమన్వయాన్ని బలోపేతం చేద్దాం.',live:'ప్రత్యక్ష కార్యకలాపాలు',maps:'మ్యాప్స్‌లో ప్రదేశాలు',shareUpdate:'కొత్త సమాచారం పంచుకోండి',inspire:'మంచి పని ప్రతి మండలానికి స్ఫూర్తి కావాలి',name:'మీ పేరు',activity:'అభివృద్ధి లేదా పార్టీ కార్యక్రమం',place:'ప్రదేశం / గ్రామం',photo:'ఫోటో',publish:'పోస్ట్ చేయండి',community:'మన వేదిక',latest:'తాజా కార్యకలాపాలు',more:'మరిన్ని చూడండి',home:'హోమ్',post:'పోస్ట్',help:'ఇన్‌స్టాల్',comments:'కామెంట్లు',send:'పంపండి',installTitle:'ఈ యాప్‌ను ఇన్‌స్టాల్ చేయండి',iosGuide:'iPhoneలో: Safariలో తెరిచి Share నొక్కి “Add to Home Screen” ఎంచుకోండి.',androidGuide:'Androidలో: బ్రౌజర్ మెనూలో “Install app” నొక్కండి.',noPosts:'మన కథ ఇక్కడ మొదలవుతుంది',firstPost:'మీ గ్రామం నుంచి మొదటి కార్యక్రమాన్ని పంచుకోండి.'}};
let lang=localStorage.lang||'te',posts=[],before=null,currentPost=null,deferredPrompt=null,photoData=null;
function id(n=24){const a=new Uint8Array(n);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(36).padStart(2,'0')).join('').slice(0,n*2)}
const device={id:localStorage.paleruDeviceId||`web-${id(20)}`,key:localStorage.paleruDeviceKey||id(32)};localStorage.paleruDeviceId=device.id;localStorage.paleruDeviceKey=device.key;
function headers(json=true){return {'X-Paleru-Device-Id':device.id,'X-Paleru-Device-Key':device.key,...(json?{'Content-Type':'application/json'}:{})}}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(options.body!==undefined),...options.headers}});if(!r.ok){let m='Request failed';try{m=(await r.json()).detail||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-i]').forEach(e=>e.textContent=words[lang][e.dataset.i]||e.textContent);$('#lang').textContent=lang==='en'?'తెలుగు':'English';localStorage.lang=lang}
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}function when(v){try{return new Intl.DateTimeFormat(lang==='te'?'te-IN':'en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return ''}}
function postCard(p){const map=p.place?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.place+', Paleru, Telangana')}`:'';return `<article class="post card" data-id="${p.id}"><div class="post-head"><div class="post-avatar">${esc(p.author_name).slice(0,1).toUpperCase()}</div><div class="post-meta"><b>${esc(p.author_name)}</b><small>${when(p.created_at)}</small></div></div><div class="post-body">${esc(p.content)}</div>${p.media_url?`<img class="post-image" loading="lazy" src="${p.media_url}" alt="Activity photo">`:''}${p.place?`<a class="place" target="_blank" rel="noopener" href="${map}">📍 ${esc(p.place)} ↗</a>`:''}<div class="counts">${p.like_count||0} 👍 · ${p.comment_count||0} 💬</div><div class="post-actions"><button data-act="like" class="${p.viewer_reaction==='like'?'active':''}">👍 <span>${lang==='te'?'ఇష్టం':'Like'}</span></button><button data-act="dislike" class="${p.viewer_reaction==='dislike'?'active':''}">👎</button><button data-act="comment">💬 <span>${lang==='te'?'కామెంట్':'Comment'}</span></button><button data-act="share">↗ <span>${lang==='te'?'షేర్':'Share'}</span></button></div></article>`}
function render(){const f=$('#feed');f.innerHTML=posts.length?posts.map(postCard).join(''):$('#empty').innerHTML;$('#more').classList.toggle('hidden',posts.length<30)}
async function load(reset=true){$('#notice').textContent=lang==='te'?'లోడ్ అవుతోంది…':'Loading…';try{const q=reset?'?limit=30':`?limit=30&before=${encodeURIComponent(before)}`,d=await api('/posts'+q);posts=reset?d.posts:[...posts,...d.posts];before=posts.at(-1)?.created_at;render();$('#notice').textContent=''}catch(e){$('#notice').textContent=(navigator.onLine?'⚠️ ':'📴 ')+e.message}}
async function compress(file){const img=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return new Promise(r=>c.toBlob(b=>{const rd=new FileReader();rd.onload=()=>r({base64:rd.result.split(',')[1],mime:b.type,url:rd.result});rd.readAsDataURL(b)},'image/jpeg',.8))}
$('#photo').onchange=async e=>{if(e.target.files[0]){photoData=await compress(e.target.files[0]);$('#preview').src=photoData.url;$('#previewWrap').classList.remove('hidden')}};$('#removePhoto').onclick=()=>{photoData=null;$('#photo').value='';$('#previewWrap').classList.add('hidden')};
$('#postForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const p=await api('/posts',{method:'POST',body:JSON.stringify({author_name:$('#name').value,content:$('#content').value,place:$('#place').value,media_base64:photoData?.base64||null,media_mime:photoData?.mime||null})});localStorage.paleruName=$('#name').value;posts.unshift(p);render();e.target.reset();$('#removePhoto').click();$('#notice').textContent=lang==='te'?'✓ పోస్ట్ ప్రచురించబడింది':'✓ Update published'}catch(x){alert(x.message)}finally{b.disabled=false}};
$('#feed').onclick=async e=>{const b=e.target.closest('button[data-act]');if(!b)return;const el=b.closest('.post'),p=posts.find(x=>x.id===el.dataset.id),act=b.dataset.act;try{if(act==='like'||act==='dislike'){const reaction=p.viewer_reaction===act?'none':act;Object.assign(p,await api(`/posts/${p.id}/reaction`,{method:'PUT',body:JSON.stringify({reaction})}));render()}else if(act==='comment')openComments(p);else{const data={title:`${p.author_name} — Paleru Congress`,text:p.content,url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.title}\n${data.text}\n${data.url}`);alert(lang==='te'?'లింక్ కాపీ అయింది':'Link copied')}}}catch(x){if(x.name!=='AbortError')alert(x.message)}};
async function openComments(p){currentPost=p;$('#comments').showModal();$('#commentList').innerHTML='…';try{const d=await api(`/posts/${p.id}/comments`);$('#commentList').innerHTML=d.comments.length?d.comments.map(c=>`<div class="comment"><b>${esc(c.author_name)}</b><p>${esc(c.content)}</p></div>`).join(''):`<p>${lang==='te'?'మొదటి కామెంట్ రాయండి.':'Be the first to comment.'}</p>`}catch(e){$('#commentList').textContent=e.message}}
$('#commentForm').onsubmit=async e=>{e.preventDefault();try{await api(`/posts/${currentPost.id}/comments`,{method:'POST',body:JSON.stringify({author_name:$('#name').value||localStorage.paleruName||'Congress member',content:$('#commentText').value})});$('#commentText').value='';await openComments(currentPost);currentPost.comment_count++;render()}catch(x){alert(x.message)}};
$('#closeComments').onclick=()=>$('#comments').close();$('#help').onclick=()=>$('#guide').showModal();$('#closeGuide').onclick=()=>$('#guide').close();$('#newPost').onclick=()=>{$('.composer').scrollIntoView({behavior:'smooth'});$('#content').focus()};$('#refresh').onclick=()=>load(true);$('#more').onclick=()=>load(false);$('#lang').onclick=()=>{lang=lang==='en'?'te':'en';translate();render()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').classList.remove('hidden')});$('#install').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#install').classList.add('hidden')}else $('#guide').showModal()};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));$('#name').value=localStorage.paleruName||'';translate();load();
